project:
  type: website
  output-dir: docs

website:
  title: "Stan Karzhev"
  navbar:
    background: "#E1E0E0"
    right:
      - about.qmd
      - projects.qmd

      - icon: github
        href: https://github.com/StanKarz
      - icon: linkedin
        href: https://www.linkedin.com/in/stanislav-karzhev-587808232/
format:
  html:
    theme: cosmos
    css: styles.css



